name: OOPirate Testing
on:
  push:
    branches:
      - ENTREGA

jobs:
  clone_and_replace:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Clone remote repository
      env:
        # PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      run: |
        git clone -b OOPirate_Tester https://github.com/eastanganelli/OOP_ObjectOrientedPirate.git test
      #  rm -rf test/*
      #  cp -r temp_repo/* test/
      #  rm -rf temp_repo
        
    - name: Running Tests
      run: pytest test
    #- name: Commit changes
    #  run: |
    #    git config --global user.name "GitHub Actions"
    #    git config --global user.email "actions@github.com"
    #    git add .
    #    git commit -m "Replace 'test' folder contents"
    #    git push